// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUTKvPEmW5MzRI8mI-aJ6t4lTvXq9pWMA',
    appId: '1:287078122278:web:69849a623555fb74f6f7e7',
    messagingSenderId: '287078122278',
    projectId: 'jpn-learning-app-115502-abddb',
    authDomain: 'jpn-learning-app-115502-abddb.firebaseapp.com',
    storageBucket: 'jpn-learning-app-115502-abddb.firebasestorage.app',
    measurementId: 'G-DVWPKQ0MT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5xbDFBlVsQ9t56DTWzxO_sNzAj-FxuV4',
    appId: '1:287078122278:android:2e68e38c713779adf6f7e7',
    messagingSenderId: '287078122278',
    projectId: 'jpn-learning-app-115502-abddb',
    storageBucket: 'jpn-learning-app-115502-abddb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2dMsmmBpjtUWIN_Ov1RZmbrfRqfZ5lSU',
    appId: '1:287078122278:ios:a26cfbc57af921bff6f7e7',
    messagingSenderId: '287078122278',
    projectId: 'jpn-learning-app-115502-abddb',
    storageBucket: 'jpn-learning-app-115502-abddb.firebasestorage.app',
    iosBundleId: 'com.example.jpnLearningAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2dMsmmBpjtUWIN_Ov1RZmbrfRqfZ5lSU',
    appId: '1:287078122278:ios:a26cfbc57af921bff6f7e7',
    messagingSenderId: '287078122278',
    projectId: 'jpn-learning-app-115502-abddb',
    storageBucket: 'jpn-learning-app-115502-abddb.firebasestorage.app',
    iosBundleId: 'com.example.jpnLearningAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUTKvPEmW5MzRI8mI-aJ6t4lTvXq9pWMA',
    appId: '1:287078122278:web:064c6afd40e245b0f6f7e7',
    messagingSenderId: '287078122278',
    projectId: 'jpn-learning-app-115502-abddb',
    authDomain: 'jpn-learning-app-115502-abddb.firebaseapp.com',
    storageBucket: 'jpn-learning-app-115502-abddb.firebasestorage.app',
    measurementId: 'G-32B5F0PDZ3',
  );
}
