"""initial schema

Revision ID: f3b1d264821d
Revises: 
Create Date: 2026-10-06 14:28:58.960289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3b1d264821d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('dialect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('jp_name', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('prompt_instruction', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('student_domains', sa.String(length=200), nullable=False),
    sa.Column('student_id_pattern', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('study_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('goal_type', sa.String(length=50), nullable=False),
    sa.Column('goal_target', sa.Integer(), nullable=False),
    sa.Column('current_progress', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('friend_id', sa.String(length=20), nullable=True),
    sa.Column('japanese_level', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('ai_cheat_sheet', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('j_pts', sa.Integer(), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=True),
    sa.Column('last_login_date', sa.Date(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('daily_scans', sa.Integer(), nullable=True),
    sa.Column('last_scan_date', sa.Date(), nullable=True),
    sa.Column('photo_count_today', sa.Integer(), nullable=True),
    sa.Column('photo_extra_count', sa.Integer(), nullable=True),
    sa.Column('ai_count_today', sa.Integer(), nullable=True),
    sa.Column('ai_extra_count', sa.Integer(), nullable=True),
    sa.Column('reading_extra_count', sa.Integer(), nullable=True),
    sa.Column('last_reset_date', sa.Date(), nullable=True),
    sa.Column('scan_credits', sa.Integer(), nullable=True),
    sa.Column('ai_credits', sa.Integer(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=True),
    sa.Column('total_active_days', sa.Integer(), nullable=True),
    sa.Column('total_scans', sa.Integer(), nullable=True),
    sa.Column('notified_levels', sa.JSON(), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('push_token', sa.String(length=255), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('subscription_end_date', sa.DateTime(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('trial_used', sa.Boolean(), nullable=True),
    sa.Column('trial_notice_sent', sa.Boolean(), nullable=True),
    sa.Column('last_free_group_week', sa.String(length=10), nullable=True),
    sa.Column('group_free_used_this_week', sa.Integer(), nullable=True),
    sa.Column('vocab_slot', sa.Integer(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.Column('teacher_status', sa.String(length=20), nullable=True),
    sa.Column('teacher_department', sa.String(length=50), nullable=True),
    sa.Column('teacher_apply_note', sa.String(length=200), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('daily_task_date', sa.Date(), nullable=True),
    sa.Column('daily_task_photo', sa.Boolean(), nullable=True),
    sa.Column('daily_task_ai', sa.Boolean(), nullable=True),
    sa.Column('daily_reward_claimed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('friend_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_push_token'), ['push_token'], unique=False)

    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon_codepoint', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=False),
    sa.Column('translation', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('grammar_points', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('unlock_cost', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('character_name', sa.String(length=50), nullable=True),
    sa.Column('dialect_id', sa.Integer(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dialect_id'], ['dialect.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('join_code', sa.String(length=10), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('grade_config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classroom_join_code'), ['join_code'], unique=True)

    op.create_table('custom_character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=True),
    sa.Column('age', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('personality', sa.String(length=100), nullable=True),
    sa.Column('special_traits', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('replied_by', sa.Integer(), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['replied_by'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friend_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['study_group.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('group_scans', sa.Integer(), nullable=True),
    sa.Column('group_points', sa.Integer(), nullable=True),
    sa.Column('group_logins', sa.Integer(), nullable=True),
    sa.Column('group_sentences', sa.Integer(), nullable=True),
    sa.Column('group_articles', sa.Integer(), nullable=True),
    sa.Column('has_claimed', sa.Boolean(), nullable=True),
    sa.Column('paid_deposit', sa.Boolean(), nullable=True),
    sa.Column('deposit_amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['study_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=256), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_code_user_id'), ['user_id'], unique=False)

    op.create_table('point_package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('point_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('related_feature', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('level_tag', sa.String(length=20), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('option_a', sa.String(length=100), nullable=False),
    sa.Column('option_b', sa.String(length=100), nullable=False),
    sa.Column('option_c', sa.String(length=100), nullable=False),
    sa.Column('option_d', sa.String(length=100), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.Column('icon_codepoint', sa.Integer(), nullable=True),
    sa.Column('show_in_quick_select', sa.Boolean(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentence_practice_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grammar_point', sa.String(length=100), nullable=False),
    sa.Column('selected_vocabs', sa.JSON(), nullable=True),
    sa.Column('user_sentence', sa.Text(), nullable=False),
    sa.Column('corrected_sentence', sa.Text(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('is_claimed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('billing_cycle', sa.String(length=10), nullable=True),
    sa.Column('price_monthly', sa.Integer(), nullable=True),
    sa.Column('price_yearly', sa.Integer(), nullable=True),
    sa.Column('features_json', sa.JSON(), nullable=True),
    sa.Column('points_grant_monthly', sa.Integer(), nullable=True),
    sa.Column('points_grant_yearly', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('target_table', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('late_policy', sa.String(length=10), nullable=True),
    sa.Column('late_penalty', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classroom_announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classroom_announcement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classroom_announcement_classroom_id'), ['classroom_id'], unique=False)

    op.create_table('classroom_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('notice_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classroom_id', 'student_id', name='uq_classroom_student')
    )
    op.create_table('reading_evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unlocked_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('custom_title', sa.String(length=100), nullable=True),
    sa.Column('context_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('billing_cycle', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_word', sa.String(length=100), nullable=True),
    sa.Column('audio_basic', sa.String(length=100), nullable=True),
    sa.Column('audio_inter', sa.String(length=100), nullable=True),
    sa.Column('audio_upper', sa.String(length=100), nullable=True),
    sa.Column('audio_adv', sa.String(length=100), nullable=True),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('kana', sa.String(length=100), nullable=False),
    sa.Column('meaning', sa.String(length=200), nullable=False),
    sa.Column('sentence_basic', sa.String(length=255), nullable=True),
    sa.Column('sentence_inter', sa.String(length=255), nullable=True),
    sa.Column('sentence_upper_inter', sa.String(length=255), nullable=True),
    sa.Column('sentence_advanced', sa.String(length=255), nullable=True),
    sa.Column('sentence_basic_zh', sa.String(length=255), nullable=True),
    sa.Column('sentence_inter_zh', sa.String(length=255), nullable=True),
    sa.Column('sentence_upper_inter_zh', sa.String(length=255), nullable=True),
    sa.Column('sentence_advanced_zh', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result_ref_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('teacher_comment', sa.Text(), nullable=True),
    sa.Column('answer_detail', sa.JSON(), nullable=True),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('ai_feedback', sa.JSON(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'student_id', name='uq_assignment_student')
    )
    op.create_table('user_photo_vocab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('vocab_id', sa.Integer(), nullable=False),
    sa.Column('context_sentence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['user_photo.id'], ),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocab.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_vocab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vocab_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['user_folder.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocab.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vocab_id', name='uq_user_vocab_user_vocab')
    )
    # school 與 user 互相參照（school.created_by_user_id → user.id、user.school_id → school.id）。
    # MySQL 建表時被參照的表必須已存在，所以這條外鍵等兩張表都建好後才補上（SQLite 會用 batch 模式重建表）。
    with op.batch_alter_table('school') as batch_op:
        batch_op.create_foreign_key('fk_school_created_by_user', 'user', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school') as batch_op:
        batch_op.drop_constraint('fk_school_created_by_user', type_='foreignkey')
    op.drop_table('user_vocab')
    op.drop_table('user_photo_vocab')
    op.drop_table('assignment_submission')
    op.drop_table('vocab')
    op.drop_table('user_subscription')
    op.drop_table('user_photo')
    op.drop_table('user_achievement')
    op.drop_table('unlocked_articles')
    op.drop_table('score_record')
    op.drop_table('reading_evaluation')
    op.drop_table('classroom_member')
    with op.batch_alter_table('classroom_announcement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classroom_announcement_classroom_id'))

    op.drop_table('classroom_announcement')
    op.drop_table('chat_message')
    op.drop_table('assignment')
    op.drop_table('article_progress')
    op.drop_table('user_folder')
    op.drop_table('system_log')
    op.drop_table('subscription_plan')
    op.drop_table('sentence_practice_record')
    op.drop_table('scene')
    op.drop_table('quiz_question')
    op.drop_table('point_transaction')
    op.drop_table('point_package')
    with op.batch_alter_table('password_reset_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_code_user_id'))

    op.drop_table('password_reset_code')
    op.drop_table('notification')
    op.drop_table('group_member')
    op.drop_table('group_invite')
    op.drop_table('friendship')
    op.drop_table('friend_request')
    op.drop_table('feedback')
    op.drop_table('custom_character')
    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classroom_join_code'))

    op.drop_table('classroom')
    op.drop_table('chat_session')
    op.drop_table('articles')
    op.drop_table('achievement')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_push_token'))

    op.drop_table('user')
    op.drop_table('study_group')
    op.drop_table('school')
    op.drop_table('dialect')
    op.drop_table('admin')
    # ### end Alembic commands ###
