name: jpn_learning_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  http: ^1.6.0
  camera: ^0.12.0
  google_mlkit_image_labeling: ^0.14.2
  google_mlkit_text_recognition: ^0.15.1
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  google_sign_in: ^7.2.0
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.3.5
  url_launcher: ^6.3.1
  timezone: ^0.9.4
  flutter_tts: ^4.2.5
  audioplayers: ^6.1.0
  speech_to_text: ^7.4.0
  confetti: ^0.8.0
  record: ^6.2.1
  path_provider: ^2.1.6
  permission_handler: ^12.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # 注意這裡：assets 必須往內縮排兩個空格
  assets:
    - assets/images/